export const topAvailedServicesData = [
  {
    serviceName: 'Oil Change',
    timesAvailed: 156,
    totalRevenue: '$7,800',
    dateAvailed: '2025-10-28',
  },
  {
    serviceName: 'Tire Rotation',
    timesAvailed: 98,
    totalRevenue: '$4,900',
    dateAvailed: '2025-10-27',
  },
  {
    serviceName: 'Brake Inspection',
    timesAvailed: 87,
    totalRevenue: '$6,525',
    dateAvailed: '2025-10-26',
  },
  {
    serviceName: 'Engine Diagnostics',
    timesAvailed: 64,
    totalRevenue: '$9,600',
    dateAvailed: '2025-10-25',
  },
  {
    serviceName: 'Air Filter Replacement',
    timesAvailed: 52,
    totalRevenue: '$2,600',
    dateAvailed: '2025-10-24',
  },
];

export const customerFeedbackData = [
  {
    name: 'John Smith',
    serviceName: 'Oil Change',
    assignedStaff: 'Mike Johnson',
    feedbackRating: '⭐⭐⭐⭐⭐',
    feedbackComment: 'Excellent service, very professional',
    feedbackDate: '2025-10-28',
  },
  {
    name: 'Sarah Williams',
    serviceName: 'Brake Inspection',
    assignedStaff: 'David Lee',
    feedbackRating: '⭐⭐⭐⭐',
    feedbackComment: 'Good work but took longer than expected',
    feedbackDate: '2025-10-27',
  },
  {
    name: 'Robert Davis',
    serviceName: 'Engine Diagnostics',
    assignedStaff: 'Mike Johnson',
    feedbackRating: '⭐⭐⭐⭐⭐',
    feedbackComment: 'Fixed the issue quickly, highly recommended',
    feedbackDate: '2025-10-26',
  },
  {
    name: 'Emily Brown',
    serviceName: 'Tire Rotation',
    assignedStaff: 'Chris Martinez',
    feedbackRating: '⭐⭐⭐⭐⭐',
    feedbackComment: 'Great service and friendly staff',
    feedbackDate: '2025-10-25',
  },
];

export const vehicleHistoryData = [
  {
    serviceDate: '2025-10-28T09:30:00.000Z',
    serviceName: 'Oil Change',
    technicianName: 'Luis Ramirez',
    serviceCost: '₱3,200.00',
    remarks: 'Replaced oil filter and topped up fluids',
    status: 'Completed',
    vehicle: 'Toyota Vios 2020',
    plateNumber: 'ABC123',
  },
  {
    serviceDate: '2025-10-29T11:00:00.000Z',
    serviceName: 'Engine Tune-Up',
    technicianName: 'Mark Santos',
    serviceCost: '₱7,500.00',
    remarks: 'Adjusted spark plugs and timing belt',
    status: 'Completed',
    vehicle: 'Honda Civic 2019',
    plateNumber: 'XYZ987',
  },
  {
    serviceDate: '2025-10-30T10:00:00.000Z',
    serviceName: 'Wheel Balancing',
    technicianName: 'Noreen Diaz',
    serviceCost: '₱5,000.00',
    remarks: 'All four tires balanced',
    status: 'Completed',
    vehicle: 'Jac Motors J3 2018',
    plateNumber: 'PLL234',
  },
  {
    serviceDate: '2025-10-26T13:15:00.000Z',
    serviceName: 'Brake Inspection',
    technicianName: 'Erwin Cruz',
    serviceCost: '₱2,800.00',
    remarks: 'Front brake pads replaced',
    status: 'Completed',
    vehicle: 'Ford Ranger 2022',
    plateNumber: 'TUV456',
  },
  {
    serviceDate: '2025-10-25T15:45:00.000Z',
    serviceName: 'Aircon Cleaning',
    technicianName: 'Jessica Lopez',
    serviceCost: '₱4,500.00',
    remarks: 'Replaced cabin filter and cleaned evaporator',
    status: 'Completed',
    vehicle: 'Mitsubishi Mirage 2021',
    plateNumber: 'HJK789',
  },
  {
    serviceDate: '2025-10-31T08:00:00.000Z',
    serviceName: 'Tire Replacement',
    technicianName: 'Rico Dela Cruz',
    serviceCost: '₱10,000.00',
    remarks: 'Replaced two tires with new ones',
    status: 'Completed',
    vehicle: 'Suzuki Ertiga 2017',
    plateNumber: 'LMS562',
  },
  {
    serviceDate: '2025-10-27T14:30:00.000Z',
    serviceName: 'Car Wash',
    technicianName: 'Amanda Reyes',
    serviceCost: '₱600.00',
    remarks: 'Full exterior and interior cleaning',
    status: 'Completed',
    vehicle: 'Hyundai Accent 2023',
    plateNumber: 'QWE908',
  },
  {
    serviceDate: '2025-10-24T10:45:00.000Z',
    serviceName: 'Battery Replacement',
    technicianName: 'Karl Mendoza',
    serviceCost: '₱6,300.00',
    remarks: 'Installed new Motolite battery',
    status: 'Completed',
    vehicle: 'Chevrolet Trailblazer 2019',
    plateNumber: 'RTY543',
  },
  {
    serviceDate: '2025-10-29T09:00:00.000Z',
    serviceName: 'Transmission Check',
    technicianName: 'Jayson Cruz',
    serviceCost: '₱8,500.00',
    remarks: 'Cleaned fluid lines and replaced transmission oil',
    status: 'Completed',
    vehicle: 'Nissan Terra 2020',
    plateNumber: 'POI321',
  },
  {
    serviceDate: '2025-10-30T16:00:00.000Z',
    serviceName: 'Suspension Repair',
    technicianName: 'Ella Morales',
    serviceCost: '₱9,200.00',
    remarks: 'Replaced shocks and bushings',
    status: 'Completed',
    vehicle: 'Mazda CX-5 2021',
    plateNumber: 'DFG111',
  },
];

export const revenueData = [
  {
    date: '2025-10-28',
    servicesCompleted: 45,
    revenue: '$2,250',
    topServices: 'Oil Change, Brake Service',
  },
  {
    date: '2025-10-27',
    servicesCompleted: 38,
    revenue: '$1,900',
    topServices: 'Tire Rotation, Diagnostics',
  },
  {
    date: '2025-10-26',
    servicesCompleted: 52,
    revenue: '$2,600',
    topServices: 'Oil Change, Engine Work',
  },
  {
    date: '2025-10-25',
    servicesCompleted: 41,
    revenue: '$2,050',
    topServices: 'Brake Service, Tire Work',
  },
  {
    date: '2025-10-24',
    servicesCompleted: 35,
    revenue: '$1,750',
    topServices: 'Oil Change, Filter Replacement',
  },
];
